### ISSUE TITLE
[Discussion] Preview Color

### ISSUE THREAD

**Issue by runyasak** [dtinth/tailwind-search#1]
Hi, P'Thai @dtinth 

First, I would like to say that this project that very awesome for me.
As Tailwind beginner, that make me comfortable for finding class. 😂

For discussion, there have some properties of color that would be previewed on text value.
Like this example below.

![image](https://user-images.githubusercontent.com/6861191/78506359-37eee880-77a3-11ea-9dbf-59dec7d3fdc6.png)

However, it would be hard to see the value of color for light color.
So, I have made the preview color as box on the side of value, instead of text.

![image](https://user-images.githubusercontent.com/6861191/78506413-8e5c2700-77a3-11ea-8448-c13e13408956.png)

If you have any feedback or other solutions, please give me a suggestion.
Or, you can tell me to send a PR for this.

Thanks 😎

**Comment by dtinth** [comment]
This sounds great, PR welcome!
