### ISSUE TITLE
https://tailwind.spacet.me/ - stopped to work

### ISSUE THREAD

**Issue by tomaszwylezek** [dtinth/tailwind-search#4]
```
Please wait — Failed: TypeError: Cannot read property 'toPlainObject' of undefined
```

![Screenshot 2020-08-04 at 15 32 18](https://user-images.githubusercontent.com/16152347/89299950-c0a16680-d667-11ea-9886-83a8319191dd.png)

**Comment by dtinth** [comment]
Hey, thanks for reporting! Let me check…

**Comment by dtinth** [comment]
@tomaszwylezek I cannot reproduce it — it works fine for me. What does it say in the JavaScript Console?

**Comment by tomaszwylezek** [comment]
@dtinth 
Right now it works fine.

But also right now it uses 1.6.2 (Searching in: https://unpkg.com/tailwindcss@1.6.2/dist/tailwind.css) so it might be an issue in `1.6.1` version.

So it could be closed 😄
